/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareRouteImport } from './routes/care'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as FishRouteImport } from './routes/fish'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoryRouteImport } from './routes/story'
import { Route as VisitRouteImport } from './routes/visit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const FishRoute = FishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/collection': typeof CollectionRoute
  '/fish': typeof FishRoute
  '/merch': typeof MerchRoute
  '/rentals': typeof RentalsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/collection': typeof CollectionRoute
  '/fish': typeof FishRoute
  '/merch': typeof MerchRoute
  '/rentals': typeof RentalsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/collection': typeof CollectionRoute
  '/fish': typeof FishRoute
  '/merch': typeof MerchRoute
  '/rentals': typeof RentalsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/collection'
    | '/fish'
    | '/merch'
    | '/rentals'
    | '/shop'
    | '/story'
    | '/visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/collection'
    | '/fish'
    | '/merch'
    | '/rentals'
    | '/shop'
    | '/story'
    | '/visit'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/collection'
    | '/fish'
    | '/merch'
    | '/rentals'
    | '/shop'
    | '/story'
    | '/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRoute
  CollectionRoute: typeof CollectionRoute
  FishRoute: typeof FishRoute
  MerchRoute: typeof MerchRoute
  RentalsRoute: typeof RentalsRoute
  ShopRoute: typeof ShopRoute
  StoryRoute: typeof StoryRoute
  VisitRoute: typeof VisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish': {
      id: '/fish'
      path: '/fish'
      fullPath: '/fish'
      preLoaderRoute: typeof FishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRoute,
  CollectionRoute: CollectionRoute,
  FishRoute: FishRoute,
  MerchRoute: MerchRoute,
  RentalsRoute: RentalsRoute,
  ShopRoute: ShopRoute,
  StoryRoute: StoryRoute,
  VisitRoute: VisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
