/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareRouteImport } from './routes/care'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as FishRouteImport } from './routes/fish'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoryRouteImport } from './routes/story'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AdminHoldsRouteImport } from './routes/admin.holds'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as CollectionCategoryRouteImport } from './routes/collection.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const FishRoute = FishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHoldsRoute = AdminHoldsRouteImport.update({
  id: '/admin/holds',
  path: '/admin/holds',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRoute,
} as any)
const CollectionCategoryRoute = CollectionCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CollectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/collection': typeof CollectionRouteWithChildren
  '/fish': typeof FishRoute
  '/merch': typeof MerchRoute
  '/rentals': typeof RentalsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
  '/admin/holds': typeof AdminHoldsRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/fish': typeof FishRoute
  '/merch': typeof MerchRoute
  '/rentals': typeof RentalsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
  '/admin/holds': typeof AdminHoldsRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/collection': typeof CollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/collection': typeof CollectionRouteWithChildren
  '/fish': typeof FishRoute
  '/merch': typeof MerchRoute
  '/rentals': typeof RentalsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/visit': typeof VisitRoute
  '/admin/holds': typeof AdminHoldsRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/collection'
    | '/fish'
    | '/merch'
    | '/rentals'
    | '/shop'
    | '/story'
    | '/visit'
    | '/admin/holds'
    | '/collection/$category'
    | '/collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/fish'
    | '/merch'
    | '/rentals'
    | '/shop'
    | '/story'
    | '/visit'
    | '/admin/holds'
    | '/collection/$category'
    | '/collection'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/collection'
    | '/fish'
    | '/merch'
    | '/rentals'
    | '/shop'
    | '/story'
    | '/visit'
    | '/admin/holds'
    | '/collection/$category'
    | '/collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRoute
  CollectionRoute: typeof CollectionRouteWithChildren
  FishRoute: typeof FishRoute
  MerchRoute: typeof MerchRoute
  RentalsRoute: typeof RentalsRoute
  ShopRoute: typeof ShopRoute
  StoryRoute: typeof StoryRoute
  VisitRoute: typeof VisitRoute
  AdminHoldsRoute: typeof AdminHoldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish': {
      id: '/fish'
      path: '/fish'
      fullPath: '/fish'
      preLoaderRoute: typeof FishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/holds': {
      id: '/admin/holds'
      path: '/admin/holds'
      fullPath: '/admin/holds'
      preLoaderRoute: typeof AdminHoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/collection/$category': {
      id: '/collection/$category'
      path: '/$category'
      fullPath: '/collection/$category'
      preLoaderRoute: typeof CollectionCategoryRouteImport
      parentRoute: typeof CollectionRoute
    }
  }
}

interface CollectionRouteChildren {
  CollectionCategoryRoute: typeof CollectionCategoryRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionCategoryRoute: CollectionCategoryRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRoute,
  CollectionRoute: CollectionRouteWithChildren,
  FishRoute: FishRoute,
  MerchRoute: MerchRoute,
  RentalsRoute: RentalsRoute,
  ShopRoute: ShopRoute,
  StoryRoute: StoryRoute,
  VisitRoute: VisitRoute,
  AdminHoldsRoute: AdminHoldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
